apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logoutput
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  strategy: {}
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: random-string-output
          emptyDir: {}
      containers:
        - image: log_output/producer:2.1
          imagePullPolicy: IfNotPresent
          name: log-output-producer
          volumeMounts:
            - name: random-string-output
              mountPath: /tmp
          resources: {}
        - image: log_output/consumer:2.1
          imagePullPolicy: IfNotPresent
          name: log-output-consumer
          volumeMounts:
            - name: random-string-output
              mountPath: /tmp
          resources: {}
status: {}
