apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logoutput
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  strategy: {}
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
      - image: log_output
        imagePullPolicy: IfNotPresent
        name: log-output-q5gb9
        resources: {}
status: {}
