apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todoapp
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  strategy: {}
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - image: todo_app:1.5
          imagePullPolicy: IfNotPresent
          name: todo-app-fjhbz
          resources: {}
          env:
            - name: PORT
              value: "3000"
status: {}
