apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-claim
spec:
  storageClassName: log-output-pingpong-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi